---
title: Regular expressions in Stata cheat sheet
author: ''
date: '2021-07-24'
slug: regular-expressions-in-stata-cheat-sheet
categories: []
tags: []
---

The cheat sheet below is based off this great [cheat sheet for regular expressions in R](https://paulvanderlaken.files.wordpress.com/2017/08/r-regular-expression-cheetsheat.pdf) by Ian Kopacka.

This is not supposed to be used as an introduction to regular expressions (have a look at the relevant help files and some of the materials shared below for this).

This is also not a complete set of anchors, characters etc for matching, but those shown should be sufficient for most tasks (certainly for what I do at least!). 

A few useful links related to regular expressions in Stata:

- [Introduction to regular expressions by StataCorp](https://www.stata.com/support/faqs/data-management/regular-expressions/)
- [Complete list of string functions in Stata (not just regular expressions)](https://www.stata.com/manuals/fnstringfunctions.pdf)
- [More comprehensive (in some respects) cheat sheet by Asjad Naqvi](https://medium.com/the-stata-guide/regular-expressions-regex-in-stata-6e5c200ef27c)
- [Presentation on regular expressions by Rose Anne Medeiros](https://www.stata.com/meeting/wcsug07/medeiros_reg_ex.pdf)

To open the pdf below in its own page click [here](/./pdf/Regular_expressions_cheat_sheet.pdf).

</br>

<style>
div.pdf {
  height: 100vh;
  width: 90vw;
  position: relative;
  left: 50%;
  right: 50%;
  margin-left: -45vw;
  margin-right: -50vw;
}
</style>

<div class = "pdf">

<body style="width:100%; height:100%; margin:0;">
    <iframe src="/./pdf/Regular_expressions_cheat_sheet.pdf" style="width:100%; height:100%;" frameborder="0"></iframe>
</body>

</div>