theme: hugo-theme-codex
title: James Thomas
languageCode: en-us
baseURL: https://jamesthomas.uk/
copyright: © {year}
params:
  dateFormat: Jan 2 2006
  github: https://github.com/james-e-thomas
  iconOrder:
    - LinkedIn
    - GitHub
  showPageTitleInTOC: no
  linkedin: https://linkedin.com/in/jamese-thomas
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
menu:
  main:
    - identifier: home
      name: home
      title: Home 
      url: /
    - identifier: posts
      name: posts
      title: Posts
      url: /posts
    - identifier: cv
      name: cv
      title: cv
      url: /cv/curricumul-vitae/